### ISSUE TITLE
r-base biocontainer image for tags newer than 3.5.1

### ISSUE THREAD

**Issue by JoseEspinosa** [BioDocker/containers#416]
Hi,

First thanks for your work!

I was searching for `r-base` biocontainers images and could not find any image tag newer than `3.5.1` (e.g. `4.0.*` or `4.1.*`):

https://quay.io/repository/biocontainers/r-base?tag=latest&tab=tags

![image](https://user-images.githubusercontent.com/6224346/133290676-39089c63-586c-44f7-b24f-fcec718b49eb.png)

Is this intended or it is just that this image has not been updated?

Thanks!

**Comment by osallou** [comment]
Hi,
Those are containers created directly from bioconda packages.
If related conda oackage has a new tag, there will be automatically on quay.io a new container.

If it does not exists, you should request on bioconda github repo for a package update  ,or best contribute with a pull request :-)

**Comment by JoseEspinosa** [comment]
Thanks @osallou for your quick response!
Actually, there are several new tags, see [here](https://anaconda.org/conda-forge/r-base/files). Although `r-base` is a package from `conda-forge` and not `bioconda`  (including the tags that are already in quay.io)

**Comment by osallou** [comment]
Conda forge and bioconda are 2 different things/repo.

Bioconda (part of biocobtainers) generates docker/singularity images, conda forge no.


So just ask bioconda for a package upgrade

**Comment by drpatelh** [comment]
Hi @osallou ! What is weird is that there doesn't seem to be an official [bioconda recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/r-base) for `r-base` so maybe the Biocontainer was added in a different way?

I think we will try to use a random (small) Bioconductor package build using the required version of R as a workaround for now. Thanks!

**Comment by osallou** [comment]
hum indeed, no idea where this comes from....

quay.io/biocontainers is bioconda owned repo

**Comment by osallou** [comment]
@bgruening any idea?

**Comment by bgruening** [comment]
https://github.com/conda-forge/r-base-feedstock/

And for those, we do not generate containers by default. Please add them to the multi-container repo.

**Comment by drpatelh** [comment]
Thanks @bgruening ! I think we will try and be kind to resources and source a simple Bioconductor package that uses that version of R. Will create a PR to multi-package-containers if required.
