### ISSUE TITLE
Finding Dockerfiles for each tagged release

### ISSUE THREAD

**Issue by pmtempy** [BioDocker/containers#418]
I'm having some difficulties finding my way around the different releases of certain tools. 

For example, the BioContainers Registry for trimmomatic (https://biocontainers.pro/tools/trimmomatic) lists several 0.39 releases (0.39--0, 0.39--1, 0.39--hdfd78af_2), but the release dates across DockerHub, Conda and Singularity are puzzling to me . Release 0.39--1 was released in 2021 in conda, but in 2019 on Docker and Singularity. Conversly, the 0.39--hdfd78af_2 version, which I assume is the most recent 0.39-2 version mentioned [here](https://bioconda.github.io/recipes/trimmomatic/README.html), doesn't have a corresponding Docker or Singularity release.

I also wanted to take a look at the Dockerfiles underlying these images, but the trimmomatic directory of the git repo (https://github.com/BioContainers/containers/tree/master/trimmomatic) only contains two older versions (0.36 and 0.38), as does the DockerHub Repo (https://hub.docker.com/r/biocontainers/trimmomatic/tags?page=1&ordering=last_updated). The Quay repo (https://quay.io/repository/biocontainers/trimmomatic?tab=tags) does host more versions, but I'm not sure if these correspond to the ones listed in the BioContainer Registry? Moreover, neither DockerHub, Quay or the Registry offer links to the underlying Dockerfiles, as far as I can tell.

Am I missing something obvious? Any guidance to help me understand these things better would be much appreciated!

**Comment by osallou** [comment]
Hi,
this is indeed a bit confusing
Images on dockerhub comes from the github.com/biocontainers repo, their Dockerfile is located in containers/toolname/toolversion directory. you can find tags fro example: https://hub.docker.com/r/biocontainers/trimmomatic/tags?page=1&ordering=last_updated

Containers in quay.io are automatically built from the bioconda package. There is no Dockerfile, they use a tool to inject package content in a busybox container (or alike)

**Comment by pmtempy** [comment]
Thanks for the quick reply!

Is the Dockerfile-based approach being phased out in favour of the bioconda-based one? Seeing as the GitHub and DockerHub repo's are lacking more recent builds (in this particular instance)?

**Comment by osallou** [comment]
nope! we have both sources.

The idea is, if a conda package exist, update it in bioconda and you'll get a container
If not, create a Dockerfile based container on github (though you can create a new bioconda package from scratch...)

Sometimes we have some Dockerfiles based on bioconda to add extra software, and have bash access to the container. This is no hard line....

Regarding version updates, it is communatory based (both bioconda/docker base)
