### ISSUE TITLE
biocontainer images on docker hub are quite large

### ISSUE THREAD

**Issue by jbedo** [BioDocker/containers#426]
The biocontainer images that are available on the docker hub appear to be quite large. Here are some examples, with a baseline comparison against the nixery.dev automatically built images:

```
REPOSITORY                   TAG                      IMAGE ID       CREATED         SIZE
biocontainers/bwa           v0.7.17_cv1              3a962903b45b   17 months ago   956MB
biocontainers/samtools      v1.9-4-deb_cv1           f210eb625ba6   2 years ago     666MB
biocontainers/bedtools      v2.27.1dfsg-4-deb_cv1    0e28c37c1c09   2 years ago     119MB
nixery.dev/shell/samtools   latest                   50e3dd2be005   N/A             122MB
nixery.dev/shell/bwa        latest                   0b6012f40381   N/A             106MB
nixery.dev/shell/bedtools   latest                   4cde0008fc72   N/A             114MB
```

These tools can be built into a docker image that is substantially smaller if only the runtime is shipped rather than the whole dev environment. Reduction of the sizes would reduce costs incurred when scaling up; are there any plans to do so?

**Comment by osallou** [comment]
Not including only *runtime* was an historic decision of biocontainers to ease usage for our main target users to have shell and basic tools included with, to ease cmd line usage, easilly extend/use with their scripts etc... as many do not *know* what is a container nor master IT.

Base image have moved several times to reduce included tools baseline (there were many with gcc etc. to ease comp for them), and somes of them are a base image (debian,..) with a simple apt-get or conda install.

So i agree this can make some images big compared to a raw based tool container, and that some improvements could be done on many containers, 
But without a minimum env setup with tool, we see many users having difficulties to use the tool in their environment..

**Comment by jbedo** [comment]
Ah that makes sense, so these containers are targeted more towards interactive use by non-experts rather than large scale analysis with workflow systems like nextflow/WDL. Thanks for clarifying.
