### ISSUE TITLE
Pls update treetime docker file

### ISSUE THREAD

**Issue by mmfacun** [BioDocker/containers#428]
Hello last update for the treetime docker image is 2years ago. May I please request an update if possible. Thank you.

https://hub.docker.com/r/biocontainers/treetime

**Comment by osallou** [comment]
Hi,
You can easilly propose an update via a pull request ;-)

Containers are created/updated help with community, there is no automatic process nor dedicated team.

If you don t feel confident to do so, we ll try to manage your request once possible

**Comment by fanninpm** [comment]
It appears that the BioContainers project does not update their images on Docker Hub anymore. Instead, you should probably pull from the **quay.io** source, as explained [here.](https://biocontainers.pro/tools/treetime)

**Comment by osallou** [comment]
Biocontainers still update containers, dockerhub/quay.io are just different target.

Conda based containers are located on quay.io while custom containers are pushed to dockerhub.

Registry web site helps you search and locate the container in both cases.

Updates are a matter of community job....  No one is paid for that. Anyone can easilly update container tool recipe to get a new version....

**Comment by osallou** [comment]
treetime is available in last version:

https://bioconda.github.io/recipes/treetime/README.html

docker pull quay.io/biocontainers/treetime:<tag>
