### ISSUE TITLE
Container request: sra-human-scrubber

### ISSUE THREAD

**Issue by mciprianoCDC** [BioDocker/containers#429]
Tool to scrub human reads from fastq files.

Git: https://github.com/ncbi/sra-human-scrubber.git
Conda: https://anaconda.org/bioconda/sra-human-scrubber
Docker: https://hub.docker.com/r/ncbi/sra-human-scrubber

The Docker container includes the database. For the conda environment, init_db.sh must be run after install to download the database.

**Comment by osallou** [comment]
Hi, will try to do that next week,

But you cabmn also simply submit a pr with the dockerfile and a few metadata requirements (just look at a few other tools)

**Comment by osallou** [comment]
I see container is already available in biocontainers via bioconda 

docker pull quay.io/biocontainers/sra-human-scrubber:<tag>
