### ISSUE TITLE
[Container request]: r-phylotools

### ISSUE THREAD

**Issue by MillironX** [BioDocker/containers#432]
`phylotools` is an R package with tools for prepping sequences for phylogenetic analyses.

## Specs (incomplete)

| Field | Value |
| --- | --- |
| `LABEL software.version` | 0.2.2 |
| `LABEL software` | r-phylotools |
| `LABEL about.summary` |Phylogenetic tools for eco-phylogenetics |
| `LABEL about.home` | https://github.com/helixcn/phylotools |
| `LABEL about.license` | SPDX:GPL-2 |

**Comment by osallou** [comment]
Hi,
seems it is a library, and not a tool. If this is the case, what is the purpose to get a container?

**Comment by osallou** [comment]
Note: needs r-base
Script xxx.R:

    install.packages("devtools")
    library(devtools)
    install_github("helixcn/phylotools", build_vignettes = TRUE)

Run: Rscript xxx.R

**Comment by MillironX** [comment]
> If this is the case, what is the purpose to get a container?

The same purpose as the entire `r-*` suite of containers: to use in portable scripts and pipelines such as Nextflow.

**Comment by osallou** [comment]
build in progress

**Comment by osallou** [comment]
container: biocontainers/phylotools:v0.2.4_cv1
