### ISSUE TITLE
QUAST issue: Singularity

### ISSUE THREAD

**Issue by cjfields** [BioDocker/containers#439]
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

This was detected using Singularity via Nextflow, using [this container](https://depot.galaxyproject.org/singularity/quast:5.0.1--py36pl526ha92aebf_0)

Based on a comment in #206 this appears to be due to locale settings within the container; notably [an alternative Docker container works fine](https://hub.docker.com/r/staphb/quast/tags) when converted to Singularity.

**Comment by osallou** [comment]
This is a bioconda based package auto converted to container.

@bgruening ?

**Comment by bgruening** [comment]
I assume this is fixed, please reopen if not.
