### ISSUE TITLE
biocontainers gatk4 tools page not in sync with latest versions

### ISSUE THREAD

**Issue by jjfarrell** [BioDocker/containers#445]
This page (https://biocontainers.pro/tools/gatk4) was last updated in Feb, 2022 and does not list the latest GATK versions. It shows the command to install gatk4:4.2.4.0--hdfd78af_0 and not the latest version. 

But the singularity version is available for gatk4:4.2.6.1--hdfd78af_0 which was updated last April 15th. 
https://depot.galaxyproject.org/singularity/gatk4:4.2.6.1--hdfd78af_0

Shouldn't this page be updating automatically to show the latest version?

**Comment by osallou** [comment]
Hi, due to cloud host issues, web site (and related update process) was down for quite some time. Has been set back just a few days ago. Now we need to wait for next container update scan.


@ypriverol can you force an update, after all those issues, we are quite behind....

**Comment by bgruening** [comment]
I hope the website is in sync now. If not please use the https://quay.io/repository/biocontainers/ and https://depot.galaxyproject.org/singularity/ sites. Those are either way the source of truth.
