### ISSUE TITLE
Container for pLannotate missing on Quay

### ISSUE THREAD

**Issue by rpetit3** [BioDocker/containers#447]
Looks like when pLannotate was added there was a issue creating the container over at Quay.

[Bioconda Link](https://bioconda.github.io/recipes/plannotate/README.html)

Tagging @mmcguffi (pLannotate dev)

**Comment by osallou** [comment]
@bgruening ? quay repo as private?

**Comment by bgruening** [comment]
@osallou yes. Its now public.

**Comment by rpetit3** [comment]
Thank you!

**Comment by mmcguffi** [comment]
Thanks so much @rpetit3 and @bgruening!
