### ISSUE TITLE
Container for sequencetools

### ISSUE THREAD

**Issue by TCLamnidis** [BioDocker/containers#452]
I would like to request a container for [sequencetools](https://github.com/stschiff/sequenceTools).

The package already exists on `bioconda::sequencetools`, but I am unsure how to port it onto biocontainers as well.

Thanks

**Comment by osallou** [comment]
Hi,
if there is a bioconda package, then it is automatically in biocontainers, see https://bioconda.github.io/recipes/sequencetools/README.html , you 'll see the container id

**Comment by TCLamnidis** [comment]
I see! thank you. Thought it needed to be created manually for the first version, like bioconda recipes. 

I will close this issue then!
