### ISSUE TITLE
Container request for r-clustree

### ISSUE THREAD

**Issue by quacksawbones** [BioDocker/containers#454]
Could I please get a container built for `r-clustree`, starting with **v0.4.4**. It is a visualisation package for showing trees in R. I would like to use this functionality in a tool in Galaxy.

URLs (latest - v0.5.0): https://github.com/lazappi/clustree
v0.4.4: https://github.com/lazappi/clustree/tree/v0.4.4

Conda Forge: https://anaconda.org/conda-forge/r-clustree

CRAN repository: https://cran.r-project.org/package=clustree

NB: Please note, I am not the owner of this package.

**Comment by osallou** [comment]
Hi,
You can submit a PR, based on other tools examples to submit the requested tool.

As a conda package, you just need to set in your Dockerfile a command like conda install for the requested tool version

**Comment by quacksawbones** [comment]
Thanks @osallou. I'll have a look and see how I go.

I'll either put the PR in here or let you know if I get stuck,

Darren

**Comment by bgruening** [comment]
Container is here: https://quay.io/repository/biocontainers/r-clustree
