### ISSUE TITLE
Container request for bamdst

### ISSUE THREAD

**Issue by tamuanand** [BioDocker/containers#456]
Container for bamdst

Repository: https://github.com/shiquan/bamdst

If it helps, [I have detailed here](https://github.com/BioContainers/containers/issues/455#issuecomment-1207280478) in a conversation with @osallou how I built a container for myself. 

Having this in bioconda/biocontainers would be useful

**Comment by tamuanand** [comment]
Hi 

As a sequel to the above, I just want to mention that I am following the [guidelines listed here for requesting a Biocontainer ](https://github.com/BioContainers/specs#241-how-to-request-a-container)
>Users can request a container by opening an issue in the [containers repository](http://github.com/BioContainers/containers/issues)

And then [following these guidelines](https://github.com/BioContainers/specs#33-how-to-create-a-docker-based-biocontainer), I wanted to create a PR and submit my Dockerfile based on this image/screenshot below - but I am unable to open a PR. 

Am I missing something or ss there something missing in the docs?

![image](https://user-images.githubusercontent.com/8467214/183275202-1cf85b82-e262-4348-83de-825d794d503a.png)

**Comment by osallou** [comment]
To create a pr, you should fork the repo, , clone your fork, add your dockerfile etc. Comlut your changes and push to your fork.

Then to create a PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork


Note regarding dockerfile. Should not set specific timezones.

**Comment by tamuanand** [comment]
Hi @osallou 

This is my first time submitting one for Biocontainers - please check https://github.com/BioContainers/containers/pull/459

Thanks

**Comment by bgruening** [comment]
I guess we can close this one now. Thanks a lot @tamuanand
