### ISSUE TITLE
Container for pasty and pbptyper missing on Quay

### ISSUE THREAD

**Issue by rpetit3** [BioDocker/containers#460]
I think the repos might be set to private.

**Comment by osallou** [comment]
@bgruening can you check?

**Comment by bgruening** [comment]
Available now. @rpetit3 this happens usually if someone merges Bioconda PR manually - and NOT using the bot.

**Comment by rpetit3** [comment]
Thank you! Great to know about merging without bot. These two were both merged using the bot, incase you think its worth looking into
