### ISSUE TITLE
Container Request for alien-hunter

### ISSUE THREAD

**Issue by sambrano** [BioDocker/containers#466]
Hello, I would like to request a container for the alien-hunter tool.

LABEL    software="alien-hunter" \ 
    base_image="biocontainers/biocontainers:vdebian-buster-backports_cv1" \ 
    container="alien-hunter" \ 
    about.summary="Interpolated Variable Order Motifs to identify horizontally acquired DNA" \ 
    about.home="http://www.sanger.ac.uk/science/tools/alien-hunter" \ 
    software.version="1.7-7-deb" \ 
    upstream.version="1.7" \ 
    version="2" \ 
    about.copyright="2006-2008 George Vernikos" \ 
    about.license="GPL-2+" \ 
    about.license_file="/usr/share/doc/alien-hunter/copyright" \ 
    extra.binaries="/usr/bin/alien_hunter" \ 
    about.tags="field::biology, field::biology:structural, implemented-in::java,:perl, interface::commandline, role::program,:utility, use::analysing" 

Thanks

**Comment by osallou** [comment]
hi,
what is your request ? container is available: https://hub.docker.com/r/biocontainers/alien-hunter/tags

**Comment by sambrano** [comment]
thanks
