### ISSUE TITLE
TargetScan 7.0

### ISSUE THREAD

**Issue by BarryDigby** [BioDocker/containers#476]
I would like to add a container for `targetscan`, the corresponding Dockerfile is available in PR #475. The container builds and is currently hosted at `docker://barryd237/targetscan`.

ViennaRNA is required to run some of the TargetScan perl scripts, which is why it is bundled with the Dockerfile.

**Comment by mboudet** [comment]
Hi,

I believe we need to have a least a clarification on the license used by targetscan. I cannot seem to find any information on this on the tool's website..

**Comment by bgruening** [comment]
We have this here: https://quay.io/repository/biocontainers/targetscan?tab=tags
