### ISSUE TITLE
Container request for nanomonsv

### ISSUE THREAD

**Issue by awgymer** [BioDocker/containers#477]
I would like to request a container for [`nanomonsv`](https://github.com/friend1ws/nanomonsv).

Its seems that it is available via `bioconda` so this should be relatively straightforward I think?

**Comment by osallou** [comment]
if in bioconda, then there is already a container on quay.io/biocontainers/nanonmonsv

**Comment by awgymer** [comment]
There does not appear to be one when I search the repository?
[Recipe here](https://bioconda.github.io/recipes/nanomonsv/README.html)
Actually looks like it may not be public?

**Comment by osallou** [comment]
@bgruening seems nanomonsv is in private on quay.io (https://quay.io/repository/biocontainers/nanomonsv?tab=tags)

**Comment by bgruening** [comment]
Done
