### ISSUE TITLE
Container request for contammix

### ISSUE THREAD

**Issue by TCLamnidis** [BioDocker/containers#478]
Hi! 

I would like to request a container for [contammix](https://github.com/plfjohnson/contamMix). 

The package is already on [bioconda](https://bioconda.github.io/recipes/contammix/README.html#package-contammix).

**Comment by osallou** [comment]
if already in bioconda, then there is a related container available on quay.io as described in related page:

quay.io/biocontainers/contammix:tag

**Comment by TCLamnidis** [comment]
Thank you!
