### ISSUE TITLE
Container request for ONCOCNV

### ISSUE THREAD

**Issue by marrip** [BioDocker/containers#480]
Hey,

I would like to create a container image for [ONCOCNV](https://github.com/BoevaLab/ONCOCNV). The problem with this tool is, that it contains several `R` and `perl` scripts which are run via a `bash` script which in turn needs to be modified prior to running it which is not practical at all. I would like the image to contain only the scripts and dependencies but not the `bash` script (alternatively refactor the bash script to allow running it with args instead of setting variables inside the script). I am not sure what BioContainers' guidelines on this is. Furthermore, the latest tagged version `v6.9` contains a bug which is fixed on the `master` branch, hence, I would like to use the latest commit for building the image. Again, not sure what kind of rules apply from your side. I asked the author to tag the latest commit with a new version but I am not certain if she will.
I already have a [`Dockerfile`](https://github.com/marrip/verktoykasse/blob/main/oncocnv/Dockerfile) that was built and tested. I guess for BioCointainers certain labels need to be added.
This is a lot of questions and edge cases, I know, but I would really like to get this image ready to be able to set up a proper nf-core module with it. Any help is highly appreciated! ☺️

**Comment by osallou** [comment]
hi,
you can create a container with the R/Perl script you need and add your own bash script or user may mount his bash script in the container at runtime (but user should be aware of that...)

If you have no upstream tag, you may add something like v6.9-1 and specify in LABEL description that it fixes something

regarding labels, biocontainers indeed request quite a few.... you can look at, as example, https://github.com/BioContainers/containers/commit/b9a9fe7a5d5fca89f23db7460893df2f6c30e42d with more detailled spec: https://github.com/BioContainers/specs/blob/master/container-specs.md

**Comment by marrip** [comment]
#481
