### ISSUE TITLE
ONCOCNV image not published as expected

### ISSUE THREAD

**Issue by marrip** [BioDocker/containers#482]
Hey again,

thank you @osallou for your help with building the ONCOCNV container image. Unfortunately, it was not pushed and published as expected. I can find it on dockerhub but not at galaxyproject.org (as singularity) or quay.io which I expected. Did I do something wrong or is this desired behavior. 🤔

**Comment by osallou** [comment]
conda based containers are on quay.io, dockerfile based are on dockerhub

for singulatiry , dockerfile base are here: https://containers.biocontainers.pro/s3/SingImgsRepo/oncocnv/v7.0_cv1/

separation between both is historic and to avoid mixing as not built the same way....

**Comment by marrip** [comment]
ok, cool, then I understand! Thanks again for all your help and input! 😉
