### ISSUE TITLE
bismark container Linux sort version

### ISSUE THREAD

**Issue by JudithR** [BioDocker/containers#483]
Hi, 

I hope this is the right place to report this issue. It refers specifically the OS part of the container, not bismark itself. 

I downloaded the docker biocontainer for bismark from quay.io (bismark:0.24.0--hdfd78af_0, although 0.23 has the same issue). 
bismark2bedGraph uses the build in sort command from the container with the following flags: `sort -S $sort_size -T $sort_dir -k3,3V -k4,4n` (lines 434++). The build-in sort of the container does not know about -S and -T, resulting in empty output files in bismark_methylation_extractor when used with the --bedgraph flag: 
```
singularity shell ~/software/singularity/bismark_0.24.0--hdfd78af_0.sif
Singularity> sort --help
BusyBox v1.32.1 (2021-04-13 11:15:36 UTC) multi-call binary.

Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...

Sort lines of text

        -o FILE Output to FILE
        -c      Check whether input is sorted
        -b      Ignore leading blanks
        -f      Ignore case
        -i      Ignore unprintable characters
        -d      Dictionary order (blank or alphanumeric only)
        -n      Sort numbers
        -g      General numerical sort
        -M      Sort month
        -V      Sort version
        -t CHAR Field separator
        -k N[,M] Sort by Nth field
        -r      Reverse sort order
        -s      Stable (don't sort ties alphabetically)
        -u      Suppress duplicate lines
        -z      Lines are terminated by NUL, not newline
```
The reported error messages are:
```
Sorting input file BK12171.trimmed_filt_merged.1_bismark_bt2_pe.bedGraph.gz.methylation_calls.merged by positions (using -S of 2G)
sort: unknown sort type
Died at /usr/local/bin/bismark2bedGraph line 487.
Finished BedGraph conversion ...
```
with finally
```
No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!
```

Would it be possible to add a more complete version of sort to the container to fix this issue?

Thank you very much
Judith

**Comment by osallou** [comment]
hi, container is build directly from bioconda package, so issue should be reported on bioconda related package itself

**Comment by JudithR** [comment]
Thanks for the quick response. I reported it there too.
Judith

**Comment by bgruening** [comment]
@JudithR has this solved by now? If not can you link me please to the bioconda issue. Thanks.

**Comment by JudithR** [comment]
Apologies for the slow response, yes the biocontainer build now contains core-utils. With thanks to dirkjanvw.
Judith
