### ISSUE TITLE
Container request for beautier

### ISSUE THREAD

**Issue by richelbilderbeek** [BioDocker/containers#485]
Dear `containers` maintainers,

By hearsay I learned that BioContainers is the place to store Singularity containers related to biological research.

I would like to request a place to store my Singularity containers for the beautier R package. It is a prerequisite for the `babette` R package (Bilderbeek & Etienne, 2018). In short, the `babette` R package allows one to create a Bayesian phylogeny distribution from DNA/RNA/protein sequences.

I'd be happy to answer more questions and/or move on from here :-)

Later, I will request to move up in the dependency hierarchy and request the storage for `beastier` (which depends on `beautier`), then `babette` (which depends on `beastier`). 

## References

 * Bilderbeek, Richèl JC, and Rampal S. Etienne. "babette: BEAUti 2, BEAST 2 and Tracer for R." Methods in Ecology and Evolution (2018). https://doi.org/10.1111/2041-210X.13032

**Comment by osallou** [comment]
Hi,
This is not a singularity repo but a docker repo.

However, we indeed also build (convert ) singularity images


So you should create a docker recipe with expected tags as explained in biocontainers doc/spec

If you create a bioconda recipe on bioconda repp, it will also create docker and singularity images

**Comment by richelbilderbeek** [comment]
Thanks @osallou, in that case it was both that I was misinformed as well as I misunderstood the last line of [https://biocontainers-edu.readthedocs.io/en/latest/what_is_biocontainers.html#biocontainers](https://biocontainers-edu.readthedocs.io/en/latest/what_is_biocontainers.html#biocontainers):

> BioContainers is based on the popular frameworks [Conda](https://conda.io/), [Docker](https://www.docker.com/) and [Singularity](https://www.sylabs.io/docs/).

Thanks for clearing that one up, I'll close the Issue :-)

**Comment by osallou** [comment]
well, as I said singularity containers are build anyway, and singularity can run docker images.... ;-)

**Comment by richelbilderbeek** [comment]
Yes, @osallou, but I don't have Docker scripts. Sure, I guess I can convert them, but instead I could also look for a Singularity-first repo. If you know one (next to the Sylabs one), would be great :-)
