### ISSUE TITLE
Containers for SyRI and plotsr missing on Quay

### ISSUE THREAD

**Issue by pcrxn** [BioDocker/containers#490]
Hello,

I'd like to request containers for [SyRI](https://anaconda.org/bioconda/syri) and [plotsr](https://anaconda.org/bioconda/plotsr), which are already on Bioconda, but missing from https://quay.io/repository/biocontainers. Might be related to #460.

Thanks!

**Comment by osallou** [comment]
Certainly an issie where repo remains private (default on quay)

@bgruening ?

**Comment by bgruening** [comment]
Fixed, thanks for reporting!
