### ISSUE TITLE
MLST script `mlst-download_pub_mlst` is missing dependencies

### ISSUE THREAD

**Issue by marrip** [BioDocker/containers#494]
Hey,

I was using [this container](https://quay.io/repository/biocontainers/mlst) and found that the script `mlst-download_pub_mlst` is missing the perl library `File::Which` and the linux tool `parallel` (maybe even more?). I could not identify any package manager (`apt`?) in the container and had to install things via `dpkg` but there are too many dependencies. Would it be possible to fix the dependencies for the script or get pointers on how to fix them? Thank you!

**Comment by osallou** [comment]
It is a container built from conda package, means recipe should be updated on bioconda side.

You may submit a patch in bioconda, once merged container will be automatically built

@bgruening any idea about this?

**Comment by marrip** [comment]
fixed it in bioconda and the latest version (`quay.io/biocontainers/mlst:2.23.0--hdfd78af_1`) contains working scripts 👍
