### ISSUE TITLE
Container request for sgdemux

### ISSUE THREAD

**Issue by nh13** [BioDocker/containers#495]
Dear maintainers,

I would like a container for [sgdemux](https://github.com/Singular-Genomics/singular-demux) to be added.  It is currently on [bioconda here](https://bioconda.github.io/recipes/sgdemux/README.html#package-sgdemux), so I would have expected it to show up automatically here: https://quay.io/repository/biocontainers/sgdemux.  Any ideas?

Sincerely,

Nils Homer

**Comment by osallou** [comment]
Seems repo is still in private.

This sometimes occurs as quay.io sets new repos as private by default

@bgruening ?

**Comment by bgruening** [comment]
Fixed.

**Comment by bgruening** [comment]
It should be now available Nils.

**Comment by nh13** [comment]
Thank you!
