### ISSUE TITLE
Container request for fqtk

### ISSUE THREAD

**Issue by sam-white04** [BioDocker/containers#499]
Hello maintainers, 

I would like a container for [fqtk](https://github.com/fulcrumgenomics/fqtk) to be added. It is currently on [bioconda here](https://bioconda.github.io/recipes/fqtk/README.html), however it is not available at https://quay.io/biocontainers/fqtk. I believe this is similar to an issue opened by @nh13 https://github.com/BioContainers/containers/issues/495.  

Thank you,

Samantha White

**Comment by osallou** [comment]
If not available, means repo must be in private. @bgruening can you check? Thanks

**Comment by bgruening** [comment]
Fixed.

**Comment by sam-white04** [comment]
@bgruening Thank you!
