### ISSUE TITLE
Container request for metaMix

### ISSUE THREAD

**Issue by sofstam** [BioDocker/containers#500]
Hello, 

I would like to request a container for metaMix R package.

https://github.com/conda-forge/r-metamix-feedstock

**Comment by osallou** [comment]
Hi
I suggest you create a pull request to add the container, a simple conda install will be enough in recipe, you just need to add metadata to dockerfile :-)

**Comment by jfy133** [comment]
Done in https://github.com/BioContainers/containers/pull/502
