### ISSUE TITLE
New container for latest ASCAT release (v3.1.1)

### ISSUE THREAD

**Issue by mauro-saporita** [BioDocker/containers#503]
A new version of ASCAT has been released in December 2022 (https://github.com/VanLoo-lab/ascat/tree/master) but the latest ASCAT biocontainer includes the version v3.0.

Would be possible to deploy a new biocontainer with the latest ASCAT version?

Thanks!

**Comment by osallou** [comment]
hi,
this is a bioconda based container, so just ask for bioconda package update and you'll get related container automatically :-)

**Comment by mauro-saporita** [comment]
Got it, I've just sent a package update request.

Many thanks!
