### ISSUE TITLE
sina: The ARB database you were trying to use is likely corrupted

### ISSUE THREAD

**Issue by nick-youngblut** [BioDocker/containers#506]
I'm using `quay.io/biocontainers/sina:1.7.1--h9aa86b4_0`:

```
sina --threads 4 --turn \
  --fasta-write-dna --lowercase none \
  --intype fasta --outtype fasta \
  --in reads.fna \
  --db SILVA_138.1_SSURef_NR99_12_06_20_opt.arb 
  -o aligned.fna
```

...and getting the following error:

```
01:15:53 [SINA] This is SINA 1.7.1.
01:15:53 [SINA] Unable to open ARB database "SILVA_138.1_SSURef_NR99_12_06_20_opt.arb".
01:15:53 [SINA] The ARB database you were trying to use is likely corrupted.
```

The accompanying db file `SILVA_138.1_SSURef_NR99_12_06_20_opt.sidx` is also present in the directory.

If I download `sina` via `wget https://github.com/epruesse/SINA/releases/download/v1.7.1/sina-1.7.1-linux.tar.gz` and run that executable, the alignment job completes successfully.

It appears that there's something wrong with the `sina` executable in the `sina:1.7.1--h9aa86b4_0` biocontainer

**Comment by osallou** [comment]
Hi, it is a conda based container, si issue is conda related, you should create an issue on bioconda related package.

Once fixed, container will be updated

Thanks

**Comment by nick-youngblut** [comment]
@osallou Thanks for the suggestion. 

I did try creating my own docker image:

```
FROM ubuntu:22.04

USER root
RUN apt-get update && \
    apt-get install -y wget python3.9 && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    apt-get clean && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/*

RUN wget https://github.com/epruesse/SINA/releases/download/v1.7.2/sina-1.7.2-linux.tar.gz && \
  tar -pzxvf sina-1.7.2-linux.tar.gz && \
  mv sina-1.7.2-linux /bin/sina-1.7.2-linux/ && \
  ln -sf /bin/sina-1.7.2-linux/bin/sina /bin/sina && \
  rm -f sina-1.7.2-linux.tar.gz

WORKDIR /data
```

... and I ran into the same error:

```
01:15:53 [SINA] This is SINA 1.7.1.
01:15:53 [SINA] Unable to open ARB database "SILVA_138.1_SSURef_NR99_12_06_20_opt.arb".
01:15:53 [SINA] The ARB database you were trying to use is likely corrupted.
```

Changing to sina 1.7.2 or Ubuntu 20.04 didn't fix the issue.

**Comment by epruesse** [comment]
That error should be issued when something went wrong calling `GB_open()` from `libARBDB.so` IIRC. So it really just couldn't open the database. Can you check whether it affects only that one file, or others? E.g. use that sina itself to convert a fasta to an arb, and see if you can open that?

**Comment by bgruening** [comment]
@nick-youngblut is this still a problem?
