### ISSUE TITLE
biocontainer failed to locate file in the mounted dir with -v

### ISSUE THREAD

**Issue by vebaev** [BioDocker/containers#507]
Hi,

I'm trying to tun a tool with biocontainer:

`sudo docker run -v /home/user/nanopore/homopolish/:/data/ quay.io/biocontainers/homopolish:0.4.1--pyhdfd78af_1 homopolish polish -a assembly.fasta -s bacteria.msh -m R9.4.pkl -o output`

It outputs `FileNotFoundError: [Errno 2] No such file or directory: 'assembly.fasta'` and the file is definitely in  `/home/user/nanopore/homopolish`

Am I missing something on the mounting syntax?

**Comment by osallou** [comment]
hi,
all depends where your allsembly.fasta is supposed to be. I think you should give full path to your files (/data/assembly.fasta ?) and/or specify working directory in your docker commande ( -w /data )

**Comment by vebaev** [comment]
I have tried both with no luck:

`sudo docker run -w /home/user/nanopore/homopolish/ -v /home/user/nanopore/homopolish/:/data/ quay.io/biocontainers/homopolish:0.4.1--pyhdfd78af_1 homopolish polish -a assembly.fasta -s bacteria.msh -m R9.4.pkl -o output`

FileNotFoundError: [Errno 2] No such file or directory: 'assembly.fasta'

`sudo docker run -w /home/user/nanopore/homopolish/ -v /home/user/nanopore/homopolish/:/data/ quay.io/biocontainers/homopolish:0.4.1--pyhdfd78af_1 homopolish polish -a /home/user/nanopore/homopolish/assembly.fasta -s bacteria.msh -m R9.4.pkl -o output`

FileNotFoundError: [Errno 2] No such file or directory: '/home/user/nanopore/homopolish/assembly.fasta'

**Comment by osallou** [comment]
you mount your home to /data in the container. File path and workding dir specified on command line refer to directories in the container.

so should be something like:

    sudo docker run -w /data -v /home/user/nanopore/homopolish/:/data/ quay.io/biocontainers/homopolish:0.4.1--pyhdfd78af_1 homopolish polish -a /data/assembly.fasta -s bacteria.msh -m R9.4.pkl -o output

**Comment by vebaev** [comment]
Thanks, it worked! :)
