### ISSUE TITLE
new Docker container with the RSAT software

### ISSUE THREAD

**Issue by eead-csic-compbio** [BioDocker/containers#515]
Good morning,
the RSAT team @jvanheld @medinaale @morganeTC @najlaksouri would like to request the creation of a new Docker BioContainer with the RSAT software, designed for the analysis of regulatory sequences in genomes. 

We have prepared and tested a Dockerfile, which you can find at 
https://github.com/rsa-tools/rsat-code/blob/master/docker/Dockerfile

You can see at the end of that file the commands we used to build and run the container locally during our tests (steps 1-5).

When this is done, the new container will replace the one at https://hub.docker.com/r/ksouri1/rsat_nksouri

Thanks for your help,
Bruno

**Comment by osallou** [comment]
hi,
you just need to create A PR with the docker file in a rsat/rsat_version directory and put in dockerfile the expected metadata folowing https://github.com/BioContainers/specs/blob/master/container-specs.md (see seaborn/0.12.2/Dockerfile for example)

**Comment by eead-csic-compbio** [comment]
Thanks, does the user need to be biodocker?

**Comment by osallou** [comment]
There is no constraint on user or base image, just recommendations.

**Comment by eead-csic-compbio** [comment]
See source at https://github.com/rsa-tools/rsat-code/blob/master/docker/Dockerfile

**Comment by eead-csic-compbio** [comment]
This is the PR: https://github.com/BioContainers/containers/pull/516

**Comment by eead-csic-compbio** [comment]
@osallou  please let us know if there's anything else we need to do. I can see the container already at https://hub.docker.com/r/biocontainers/rsat , but it still lacks a manifest?

**Comment by osallou** [comment]
Manifest? What do you mean?

Dockerfile does not appear on dockerhub (only for containers built on hub)

You have container and related tag.

Will be findable in biocontainers repo search page soon

**Comment by eead-csic-compbio** [comment]
> Manifest? What do you mean?
> 
> Dockerfile does not appear on dockerhub (only for containers built on hub)
> 
> You have container and related tag.
> 
> Will be findable in biocontainers repo search page soon

I tried to pull it and got:

    docker pull biocontainers/rsat:latest
    Error response from daemon: manifest for biocontainers/rsat:latest not found: manifest unknown: manifest unknown

However, this works:

    docker pull biocontainers/rsat:20230602_cv1

**Comment by osallou** [comment]
There is no latest, latest is not reproducible/fair

You need to specify the tag value

**Comment by eead-csic-compbio** [comment]
OK I guess I can close this issue now
