### ISSUE TITLE
 Add AllCatchR container #518 

### ISSUE THREAD

**Issue by NadineWolgast** [BioDocker/containers#520]
Hey all, I wanted to ask, if there is a tutorial on how to add a container for an devtools R package. 
I want to add a container for the tool ALLCatchR from https://github.com/ThomasBeder/ALLCatchR. I've wrote the Dockerfile for it and a pull request #518, but I'm not sure if my installation RUN statement is correct. I'd appreciate any help.

**Comment by osallou** [comment]
seems you expect R is already installed as well as devtools, which is not the case on base image

**Comment by osallou** [comment]
maybe you should base your container on r-base image


    FROM r-base:4.3.0
    .... set your  LABELS
    RUN R -e "install.packages(\"devtools\")"
    ...

**Comment by NadineWolgast** [comment]
Thank you! I will try it.
