### ISSUE TITLE
Container for Evidential Gene

### ISSUE THREAD

**Issue by avani-bhojwani** [BioDocker/containers#522]
Hello,
I made [this ](https://github.com/BioContainers/containers/pull/521) pull request earlier for a container for Evidential Gene. I was wondering if there's anything else I need to do before it becomes available on quay?
Thanks

**Comment by avani-bhojwani** [comment]
@osallou Hi, just bumping this question related to a pull request you approved earlier in June

**Comment by neoformit** [comment]
For additional context, the PR has been merged but there seems to be no image available on quay.io

**Comment by osallou** [comment]
You should ping someone on bioconda side in this case, there some occasional issues where quayio repo remains private, so image is not public.

They just need to set it to public

**Comment by avani-bhojwani** [comment]
Can you advise who I can ping? I noticed @bgruening  was tagged in similar issues previously.
Edit: I just found the list of core contributors (https://bioconda.github.io/)

**Comment by bgruening** [comment]
@osallou this was a Dockerfile PR. Not a Bioconda PR. Ball is back on your side ;-)

**Comment by osallou** [comment]
Ohh i saw quayio ref, so supposed it was a bioconda package.

If pr is made on this repo with a docker file,  container should be on dockerhib, not quayio

**Comment by osallou** [comment]
See https://hub.docker.com/r/biocontainers/evidential-gene

**Comment by avani-bhojwani** [comment]
Got it, thank you!
