### ISSUE TITLE
Please add matplotlib for pandas biocontainer

### ISSUE THREAD

**Issue by erinyoung** [BioDocker/containers#523]
Hi! 

I'd like to request adding matplotlib to the pandas 1.5.1 biocontainer. It's for creating figures with pandas.

> ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

**Comment by osallou** [comment]
Software mixing should be avoided in containers.

You just need to exec a matplotlib container on your results in a second step

**Comment by erinyoung** [comment]
Thank you for your reply!

I like creating figures from dataframes with pandas, such as boxplots. Pandas' savefig function, however, requires matplotlib. It saddens me that this is not available in biocontainers because matplotlib was not installed.

**Comment by osallou** [comment]
Ok, as i understand it is a panda lib that requires matplotlib as dependency.

Would make sense to include it in such case..  which panda image do you refer to?
If it is based on bioconda recipe, request should be made on bioconda package to a matplotlib as dependency in package, and container will be updated

**Comment by erinyoung** [comment]
I was trying to use [quay.io/biocontainers/pandas](https://quay.io/repository/biocontainers/pandas?tab=tags) with the tag 1.5.2

**Comment by osallou** [comment]
This is indeed a bioconda based container, so you should fill an issie or make a pr on bioconda recipe

**Comment by erinyoung** [comment]
Thanks!
