### ISSUE TITLE
Container request for kinship-read

### ISSUE THREAD

**Issue by TCLamnidis** [BioDocker/containers#531]
HI!

I would like to request a container for Relationship Estimation from Ancient DNA (READ). 
https://bitbucket.org/tguenther/read/src/master/

A bioconda package already exists for the tool: https://bioconda.github.io/recipes/kinship-read/README.html#package-kinship-read

**Comment by osallou** [comment]
if a bioconda package exists, a container exists, cf in related doc:

docker pull quay.io/biocontainers/kinship-read:<tag>

but you need to specify version tag

**Comment by TCLamnidis** [comment]
Thanks! I keep making the same mistake. 
Maybe this note can be added to the [README](https://github.com/BioContainers/containers#241-how-to-request-a-container)? Or maybe a "Request a container" issue template could be added that mentions this?
