### ISSUE TITLE
Web not properly working

### ISSUE THREAD

**Issue by karel-brinda** [BioDocker/containers#537]
Hello, I'm not sure if this is the right place to report this, but the web of Biocontainers doesn't seem to be working properly.

If I search eg bwa in https://biocontainers.pro/registry?all_fields_search=bwa&sort_order=asc&sort_field=default&offset=0&limit=30, it cannot find anything.

If I access the corresponding address manually, e.g., https://biocontainers.pro/tools/bwa, it shows an empty page.

**Comment by ypriverol** [comment]
I will try to fix the API, it is probably a bug on it. I will let you know.

**Comment by ypriverol** [comment]
Can you try now? Apparently was an IT temporary issue.

**Comment by karel-brinda** [comment]
Yes, it's working now. Thanks!
