### ISSUE TITLE
Update the meme biocontainer to version 5.5.5 and include graphicsmagick

### ISSUE THREAD

**Issue by thondeboer** [BioDocker/containers#556]
Seems that version 5.5.4 of meme is broken since I am getting weird results when trying to run `sea`. 5.5.5 original docker image works with the same command, but that cannot be used in nextflow, since that docker image does not have ps installed (huh?)

Also would like to see graphicsmagick installed (or whatever allows us to create png files) but I guess we can make a multi-tool container for that.

Let me know how I can help..

```
memesuite sea --p Riboseq_Starvation.fiveprimeutrs.fa --m Homo_sapiens.dna_encoded.meme --o /tmp/noot
# Checking alphabets in 1 motif files.
# Loading motifs from file 'Homo_sapiens.dna_encoded.meme'
# Alphabet: DNA
# Warning: No hold-out set was created because the primary hold-out set 
#          would have had fewer than 5 sequences.
# Positive sequences "Riboseq_Starvation.fiveprimeutrs.fa" - training: 7 hold-out: 0
# Negative sequences are shuffled primary sequences (2-order) - training: 7 hold-out: 0
# Estimating background model from control sequences.
# Background: A 0.226 C 0.274 G 0.274 T 0.226
# Background order: 2 Background size: 84
# Using Fisher Exact test for p-values.
Bad file name.8/98
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
Bad file name.
FATAL: Template does not contain data section.
```

**Comment by thondeboer** [comment]
FYI, memesuite here is a simple function I use to run memesuite from biocontainers:

```bash
memesuite() {
    DIRS="-v ${HOME}:${HOME} -v $(pwd):$(pwd) -v "/mnt/data:/mnt/data" -w $(pwd)"
    command ${DOCKER} ${DIRS} quay.io/biocontainers/meme:5.5.4--pl5321hda358d9_0 "$@"
}
```

**Comment by mboudet** [comment]
Hello,

The meme container is managed by bioconda, so any issues should be reported on their side of things.
However, I believe a 5.5.5 image is now available on their side?

https://bioconda.github.io/recipes/meme/README.html
https://quay.io/repository/biocontainers/meme

Is this the image you mentioned with '5.5.5 original docker image', or another one?

**Comment by thondeboer** [comment]
hmm..OK..Somewhat confused about who does what then, but there is no biocontainer at quay.io with 5.5.5 (4.11 seems to be the latest) and while 5.5.5 is available in conda, there is no container with 5.5.5 there...
I was talking about the "official" meme docker image at https://hub.docker.com/r/memesuite/memesuite
That is a big image also containing the web server etc. but that version is not something you can run in nextflow due to the lack of ps.

In the mean time I have pushed my own version of meme 5.5.5 to github containers for my own use, but that is a big image and not a nice small one like you guys build..I used the official biocontainer image, but did not make it small

ghcr.io/thondeboer/memesuite:5.5.5

**Comment by mboudet** [comment]
As far as I can tell, the 5.5.5 is available on [quay.io](https://quay.io/repository/biocontainers/meme?tab=tags)
quay.io/biocontainers/meme:5.5.5--pl5321hda358d9_0

Everything on quay.io is a container build from bioconda packages directly.
Everything on the dockerhub is built from this repository (and unrelated from bioconda, except that we avoid having duplicate if we can).
Usually, any bioconda package should have an equivalent image on quay.io, for every version. Sometime there is some latency however.

**Comment by thondeboer** [comment]
Ooohhh. Great. Thanks for the info. Regards,ThonOn Jan 22, 2024, at 01:24, mboudet ***@***.***> wrote:﻿
As far as I can tell, the 5.5.5 is available on quay.io
quay.io/biocontainers/meme:5.5.5--pl5321hda358d9_0
Everything on quay.io is a container build from bioconda packages directly.
Everything on the dockerhub is built from this repository (and unrelated from bioconda, except that we avoid having duplicate if we can).
Usually, any bioconda package should have an equivalent image on quay.io, for every version. Sometime there is some latency however.
