### ISSUE TITLE
Questions: container registries

### ISSUE THREAD

**Issue by sunyi000** [BioDocker/containers#562]
I have a quick question:

Where are the container images stored? 
From the architecture diagram, it seems that biocontainer uses both quay.io and dockerhub, but how do I know which image is in which registry? 

Thanks

**Comment by k-dominik** [comment]
If I may add to that question a concrete example:

There's dockerfiles for ilastik: https://github.com/BioContainers/containers/tree/master/ilastik
How would I know where to find a container. The [search on biocontainers.pro](https://biocontainers.pro/registry?all_fields_search=ilastik&sort_order=asc&sort_field=default&offset=0&limit=30) does not really turn up anything useful. Should it?

Also I found the container then on dockerhub, should it also be on quay.io, or are these used exclusively?

**Comment by mboudet** [comment]
Hello,

So, there are two main sources of docker images:

* This repository, which build the images on https://hub.docker.com/orgs/biocontainers/repositories
* The [bioconda channel recipes](https://github.com/bioconda/bioconda-recipes), where every conda package built has a docker image available on quay.io: [Example](https://quay.io/repository/biocontainers/genoboo)

So, for [ilastik](https://github.com/BioContainers/containers/tree/master/ilastik), the image will be [here](https://hub.docker.com/repository/docker/biocontainers/ilastik/general)

Sorry, the readme is not very clear, I have been meaning to rewrite it.
Regarding biocontainers, it should return relevant information, but the backend seems to be bugged at the moment.
