### ISSUE TITLE
cnv_facets is missing fonts

### ISSUE THREAD

**Issue by stianlagstad** [BioDocker/containers#566]
I am using this docker image for [cnv_facets](https://bioconda.github.io/recipes/cnv_facets/README.html): `quay.io/biocontainers/cnv_facets:0.16.0--py38r36h4b26f60_1`

This docker image can produce a few plots, which appear weird because (or at least I think it's because) of missing fonts. Here's an example (from https://github.com/dariober/cnv_facets/issues/38):
![120086527-e6f52e80-c0df-11eb-9fa8-a716e403c3c0](https://github.com/BioContainers/containers/assets/4340859/fd3eb96a-5967-428c-9905-c0dcebacd665)

I tried to look into this myself, to see how I can build the docker image locally, but I'm not sure whether the bioconda recipe for cnv_facets is working at the moment, ref https://github.com/bioconda/bioconda-recipes/issues/46927. I however thought that it could be useful to have a separate issue for the missing fonts in the docker image here.

Any tips on how to fix this issue would be greatly appreciated.

**Comment by mboudet** [comment]
Hello,

The docker image for quay.io/biocontainers/cnv_facets is built automatically on the bioconda side, and not in this repository.
Fixing the issue in bioconda should automatically fix the docker image.

**Comment by stianlagstad** [comment]
Thank you very much for responding. I have tried to use the package directly with conda, and then it produces the plot that I expect. Do you happen to have any pointers as to how the docker image for it is built?

**Comment by martin-g** [comment]
You could try using [extended-base](https://bioconda.github.io/developer/dockerfile-inventory.html?highlight=extended) image for more fonts.
See https://github.com/bioconda/bioconda-recipes/blob/e9b59e5c80db76a16b4e970249807aad1f58f94e/recipes/mgkit/meta.yaml#L99 for example

**Comment by mboudet** [comment]
Not quite sure about the build process on the bioconda side, sorry. I add assumed it was a simple 'conda install' in the containers, but if the behaviour is different, I'm not sure...

You could make an issue on the [bioconda-recipe repository](https://github.com/bioconda/bioconda-recipes)
