### ISSUE TITLE
pairix container missing Perl dependency

### ISSUE THREAD

**Issue by adthrasher** [BioDocker/containers#567]
The [pairix container](https://quay.io/repository/biocontainers/pairix?tab=info) includes a number of Perl scripts from the [source repo](https://github.com/4dn-dcic/pairix), but there is no Perl interpreter installed in the container.

**Comment by mboudet** [comment]
Hi,

Since this is a quay.io image, this is an image built from the bioconda pairix package. You may wish to make an issue in the [bioconda-recipe repository](https://github.com/bioconda/bioconda-recipes) instead
